### ISSUE TITLE
2022-9-27: DSP updated today 

### ISSUE THREAD

**Issue by jk191** [appuns/DSPMultiplyStackSize#3]
Hi, DSP updated today, and now I get this error when I start the game.

![DPS](https://user-images.githubusercontent.com/108146293/192435982-0a7c5f88-6219-4b7c-9a91-51117936ecd4.jpg)

**Comment by TakeyaSaito** [comment]
can confirm, this is happening since the update

**Comment by appuns** [comment]
Supported the game version 0.9.27.14553.
check new version

**Comment by jk191** [comment]
> Supported the game version 0.9.27.14553. check new version

thanks, that helps a lot.
